/*
 Mouse
Copyright (C) 2026 GUI

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program. If not, see <https://www.gnu.org/licenses/>
*/

#pragma once

#include <stdbool.h>

enum keyboard_overlay_key {
	KEYBOARD_KEY_W,
	KEYBOARD_KEY_A,
	KEYBOARD_KEY_S,
	KEYBOARD_KEY_D,
	KEYBOARD_KEY_SPACE,
	KEYBOARD_KEY_SHIFT,
	KEYBOARD_KEY_CTRL,
	KEYBOARD_KEY_Q,
	KEYBOARD_KEY_E,
	KEYBOARD_KEY_R,
	KEYBOARD_KEY_F,
	KEYBOARD_KEY_TAB,
	KEYBOARD_KEY_CAPS,
	KEYBOARD_KEY_1,
	KEYBOARD_KEY_2,
	KEYBOARD_KEY_3,
	KEYBOARD_KEY_4,
	KEYBOARD_KEY_5,
	KEYBOARD_KEY_ESCAPE,
	KEYBOARD_KEY_F1,
	KEYBOARD_KEY_F2,
	KEYBOARD_KEY_F3,
	KEYBOARD_KEY_F4,
	KEYBOARD_KEY_F5,
	KEYBOARD_KEY_F6,
	KEYBOARD_KEY_F7,
	KEYBOARD_KEY_F8,
	KEYBOARD_KEY_F9,
	KEYBOARD_KEY_F10,
	KEYBOARD_KEY_F11,
	KEYBOARD_KEY_F12,
	KEYBOARD_KEY_PRINT_SCREEN,
	KEYBOARD_KEY_SCROLL_LOCK,
	KEYBOARD_KEY_PAUSE,
	KEYBOARD_KEY_GRAVE,
	KEYBOARD_KEY_6,
	KEYBOARD_KEY_7,
	KEYBOARD_KEY_8,
	KEYBOARD_KEY_9,
	KEYBOARD_KEY_0,
	KEYBOARD_KEY_MINUS,
	KEYBOARD_KEY_EQUAL,
	KEYBOARD_KEY_BACKSPACE,
	KEYBOARD_KEY_T,
	KEYBOARD_KEY_Y,
	KEYBOARD_KEY_U,
	KEYBOARD_KEY_I,
	KEYBOARD_KEY_O,
	KEYBOARD_KEY_P,
	KEYBOARD_KEY_LEFT_BRACKET,
	KEYBOARD_KEY_RIGHT_BRACKET,
	KEYBOARD_KEY_BACKSLASH,
	KEYBOARD_KEY_G,
	KEYBOARD_KEY_H,
	KEYBOARD_KEY_J,
	KEYBOARD_KEY_K,
	KEYBOARD_KEY_L,
	KEYBOARD_KEY_SEMICOLON,
	KEYBOARD_KEY_APOSTROPHE,
	KEYBOARD_KEY_ENTER,
	KEYBOARD_KEY_Z,
	KEYBOARD_KEY_X,
	KEYBOARD_KEY_C,
	KEYBOARD_KEY_V,
	KEYBOARD_KEY_B,
	KEYBOARD_KEY_N,
	KEYBOARD_KEY_M,
	KEYBOARD_KEY_COMMA,
	KEYBOARD_KEY_PERIOD,
	KEYBOARD_KEY_SLASH,
	KEYBOARD_KEY_RIGHT_SHIFT,
	KEYBOARD_KEY_LEFT_ALT,
	KEYBOARD_KEY_LEFT_WINDOWS,
	KEYBOARD_KEY_RIGHT_ALT,
	KEYBOARD_KEY_RIGHT_WINDOWS,
	KEYBOARD_KEY_MENU,
	KEYBOARD_KEY_RIGHT_CTRL,
	KEYBOARD_KEY_INSERT,
	KEYBOARD_KEY_HOME,
	KEYBOARD_KEY_PAGE_UP,
	KEYBOARD_KEY_DELETE,
	KEYBOARD_KEY_END,
	KEYBOARD_KEY_PAGE_DOWN,
	KEYBOARD_KEY_UP,
	KEYBOARD_KEY_LEFT,
	KEYBOARD_KEY_DOWN,
	KEYBOARD_KEY_RIGHT,
	KEYBOARD_KEY_NUM_LOCK,
	KEYBOARD_KEY_NUMPAD_DIVIDE,
	KEYBOARD_KEY_NUMPAD_MULTIPLY,
	KEYBOARD_KEY_NUMPAD_SUBTRACT,
	KEYBOARD_KEY_NUMPAD_7,
	KEYBOARD_KEY_NUMPAD_8,
	KEYBOARD_KEY_NUMPAD_9,
	KEYBOARD_KEY_NUMPAD_ADD,
	KEYBOARD_KEY_NUMPAD_4,
	KEYBOARD_KEY_NUMPAD_5,
	KEYBOARD_KEY_NUMPAD_6,
	KEYBOARD_KEY_NUMPAD_1,
	KEYBOARD_KEY_NUMPAD_2,
	KEYBOARD_KEY_NUMPAD_3,
	KEYBOARD_KEY_NUMPAD_0,
	KEYBOARD_KEY_NUMPAD_DECIMAL,
	KEYBOARD_KEY_NUMPAD_ENTER,
	KEYBOARD_KEY_COUNT,
};

enum keyboard_capture_layout {
	KEYBOARD_LAYOUT_WASD,
	KEYBOARD_LAYOUT_100,
	KEYBOARD_LAYOUT_EDITING,
	KEYBOARD_LAYOUT_NUMPAD,
	KEYBOARD_LAYOUT_COUNT,
};

struct keyboard_capture_snapshot {
	bool pressed[KEYBOARD_KEY_COUNT];
	long press_sequences[KEYBOARD_KEY_COUNT];
};

bool keyboard_capture_initialize(void);
void keyboard_capture_shutdown(void);

/* Every source receives the same state and press sequences. With Raw Input, a
 * sequence also preserves a complete press that occurs between source ticks. */
void keyboard_capture_sample(enum keyboard_capture_layout layout, bool arrow_aliases,
				     struct keyboard_capture_snapshot *snapshot);
